language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE patienttracker;" -U postgres  
script: 
  - 'cd patienttracker/'
  - 'coverage run --source='.' manage.py test'
  - 'coverage report'
after_success:
  - coveralls